# Generated by Django 4.1 on 2022-08-22 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_blog_user_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='user_photo',
        ),
    ]
